"""
Gera src/data/blogPostsMeta.ts a partir de blogPosts.ts.
Extrai só os campos de metadados (sem content) e pré-calcula readingTime.
Execute: python scripts/gen-blog-meta.py
"""
import re
import os

SRC = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'blogPosts.ts')
DST = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'blogPostsMeta.ts')

with open(SRC, encoding='utf-8') as f:
    raw = f.read()

# ── Extract categories export ──────────────────────────────────────────────────
cat_match = re.search(r'export const categories\s*=\s*(\[.*?\]);', raw, re.DOTALL)
categories_block = cat_match.group(0) if cat_match else 'export const categories: string[] = [];'

# ── Split individual post blocks ───────────────────────────────────────────────
# Each post starts with "  {\n    id:" and ends with "  },"
# We look for each top-level object in the blogPosts array.
# Strategy: find positions of "  {\n    id:" and split there.
post_blocks = re.split(r'\n  (?=\{)', raw)

posts = []
for block in post_blocks:
    if 'id:' not in block or 'slug:' not in block:
        continue

    def extract(field, block):
        # Matches: field: "value" or field: 'value' or field: number
        m = re.search(rf'\b{field}:\s*(["\'])(.+?)\1', block, re.DOTALL)
        if m:
            return m.group(2).replace('\\n', '\n').replace('\\"', '"').replace("\\'", "'")
        m2 = re.search(rf'\b{field}:\s*(\d+)', block)
        if m2:
            return int(m2.group(1))
        return None

    post_id       = extract('id', block)
    slug          = extract('slug', block)
    category      = extract('category', block)
    title         = extract('title', block)
    meta_desc     = extract('metaDescription', block)
    keyword       = extract('keyword', block)
    date          = extract('date', block)
    summary       = extract('summary', block)

    if not slug:
        continue

    # ── Extract content to compute readingTime ─────────────────────────────────
    # Content is in a template literal: content: `...`
    cm = re.search(r'content:\s*`(.*?)`\s*[,}]', block, re.DOTALL)
    reading_time = 3  # fallback
    if cm:
        words = len(cm.group(1).split())
        reading_time = max(1, -(-words // 200))  # ceiling division

    posts.append({
        'id': post_id,
        'slug': slug,
        'category': category,
        'title': title,
        'metaDescription': meta_desc,
        'keyword': keyword,
        'date': date,
        'summary': summary,
        'readingTime': reading_time,
    })

def ts_str(v):
    if v is None:
        return '""'
    escaped = str(v).replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'

lines = [
    '// AUTO-GENERATED by scripts/gen-blog-meta.py — DO NOT EDIT MANUALLY',
    '// Run `python scripts/gen-blog-meta.py` to regenerate after adding posts.',
    '',
    'export interface BlogPostMeta {',
    '  id: number;',
    '  slug: string;',
    '  category: string;',
    '  title: string;',
    '  metaDescription: string;',
    '  keyword: string;',
    '  date: string;',
    '  summary: string;',
    '  readingTime: number;',
    '}',
    '',
    'export const blogPostsMeta: BlogPostMeta[] = [',
]

for p in posts:
    lines.append('  {')
    lines.append(f'    id: {p["id"]},')
    lines.append(f'    slug: {ts_str(p["slug"])},')
    lines.append(f'    category: {ts_str(p["category"])},')
    lines.append(f'    title: {ts_str(p["title"])},')
    lines.append(f'    metaDescription: {ts_str(p["metaDescription"])},')
    lines.append(f'    keyword: {ts_str(p["keyword"])},')
    lines.append(f'    date: {ts_str(p["date"])},')
    lines.append(f'    summary: {ts_str(p["summary"])},')
    lines.append(f'    readingTime: {p["readingTime"]},')
    lines.append('  },')

lines.append('];')
lines.append('')
lines.append(categories_block)
lines.append('')

with open(DST, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'OK  Generated {len(posts)} posts -> {DST}')
